import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";

import { DisplayText, DisplayTextM, SubHeading, HeadingH1, HeadingH2, HeadingH3, HeadingH4, HeadingH5, HeadingH6, ParagraphP1, ParagraphP2, ParagraphP3, ButtonText, ButtonText2 } from "@/components/Typography"; 

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Sebastian Pytka | Web Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sora.variable} antialiased`}
      >
        <Header />

        <div className="flex gap-4">
          <DisplayText level={1} weight="regular">Heading Regular</DisplayText>
          <DisplayText level={1} weight="semibold">Heading SemiBold</DisplayText>
          <DisplayText level={1} weight="bold">Heading Bold</DisplayText>
          <DisplayText level={1} weight="extrabold">Heading ExtraBold</DisplayText>
        </div>

        <div className="flex gap-4">
          <DisplayText level={1} weight="regular" variant="outline">Heading Regular</DisplayText>
          <DisplayText level={1} weight="semibold" variant="outline">Heading SemiBold</DisplayText>
          <DisplayText level={1} weight="bold" variant="outline">Heading Bold</DisplayText>
          <DisplayText level={1} weight="extrabold" variant="outline">Heading ExtraBold</DisplayText>
        </div>

        <div className="flex gap-4">
          <DisplayTextM level={2} weight="regular">Heading Regular</DisplayTextM>
          <DisplayTextM level={2} weight="semibold">Heading SemiBold</DisplayTextM>
          <DisplayTextM level={2} weight="bold">Heading Bold</DisplayTextM>
          <DisplayTextM level={2} weight="extrabold">Heading ExtraBold</DisplayTextM>
        </div>

        <div className="flex gap-4">
          <DisplayTextM level={2} weight="regular" variant="outline">Heading Regular</DisplayTextM>
          <DisplayTextM level={2} weight="semibold" variant="outline">Heading SemiBold</DisplayTextM>
          <DisplayTextM level={2} weight="bold" variant="outline">Heading Bold</DisplayTextM>
          <DisplayTextM level={2} weight="extrabold" variant="outline">Heading ExtraBold</DisplayTextM>
        </div>

        <div className="flex gap-4">
          <SubHeading level={2} weight="regular">Sub Heading Regular</SubHeading>
          <SubHeading level={2} weight="semibold">Sub Heading SemiBold</SubHeading>
          <SubHeading level={2} weight="bold">Sub Heading Bold</SubHeading>
          <SubHeading level={2} weight="extrabold">Sub Heading ExtraBold</SubHeading>
        </div>

        <div className="flex gap-4">
          <HeadingH1 level={1} weight="regular">Heading H1 Regular</HeadingH1>
          <HeadingH1 level={1} weight="semibold">Heading H1 SemiBold</HeadingH1>
          <HeadingH1 level={1} weight="bold">Heading H1 Bold</HeadingH1>
          <HeadingH1 level={1} weight="extrabold">Heading H1 ExtraBold</HeadingH1>
        </div>

        <div className="flex gap-4">
          <HeadingH2 level={2} weight="regular">Heading H2 Regular</HeadingH2>
          <HeadingH2 level={2} weight="semibold">Heading H2 SemiBold</HeadingH2>
          <HeadingH2 level={2} weight="bold">Heading H2 Bold</HeadingH2>
          <HeadingH2 level={2} weight="extrabold">Heading H2 ExtraBold</HeadingH2>
        </div>

        <div className="flex gap-4">
          <HeadingH3 level={3} weight="regular">Heading H3 Regular</HeadingH3>
          <HeadingH3 level={3} weight="semibold">Heading H3 SemiBold</HeadingH3>
          <HeadingH3 level={3} weight="bold">Heading H3 Bold</HeadingH3>
          <HeadingH3 level={3} weight="extrabold">Heading H3 ExtraBold</HeadingH3>
        </div>

        <div className="flex gap-4">
          <HeadingH4 level={4} weight="regular">Heading H4 Regular</HeadingH4>
          <HeadingH4 level={4} weight="semibold">Heading H4 SemiBold</HeadingH4>
          <HeadingH4 level={4} weight="bold">Heading H4 Bold</HeadingH4>
          <HeadingH4 level={4} weight="extrabold">Heading H4 ExtraBold</HeadingH4>
        </div>

        <div className="flex gap-4">
          <HeadingH5 level={5} weight="regular">Heading H5 Regular</HeadingH5>
          <HeadingH5 level={5} weight="semibold">Heading H5 SemiBold</HeadingH5>
          <HeadingH5 level={5} weight="bold">Heading H5 Bold</HeadingH5>
          <HeadingH5 level={5} weight="extrabold">Heading H5 ExtraBold</HeadingH5>
        </div>

        <div className="flex gap-4">
          <HeadingH6 level={6} weight="regular">Heading H6 Regular</HeadingH6>
          <HeadingH6 level={6} weight="semibold">Heading H6 SemiBold</HeadingH6>
          <HeadingH6 level={6} weight="bold">Heading H6 Bold</HeadingH6>
          <HeadingH6 level={6} weight="extrabold">Heading H6 ExtraBold</HeadingH6>
        </div>

        <div className="flex gap-4">
          <ParagraphP1 weight="regular">Paragraph P1 Regular</ParagraphP1>
          <ParagraphP1 weight="semibold">Paragraph P1 SemiBold</ParagraphP1>
          <ParagraphP1 weight="bold">Paragraph P1 Bold</ParagraphP1>
          <ParagraphP1 weight="extrabold">Paragraph P1 ExtraBold</ParagraphP1>
        </div>

        <div className="flex gap-4">
          <ParagraphP2 weight="regular">Paragraph P2 Regular</ParagraphP2>
          <ParagraphP2 weight="semibold">Paragraph P2 SemiBold</ParagraphP2>
          <ParagraphP2 weight="bold">Paragraph P2 Bold</ParagraphP2>
          <ParagraphP2 weight="extrabold">Paragraph P2 ExtraBold</ParagraphP2>
        </div>

        <div className="flex gap-4">
          <ParagraphP3 weight="regular">Paragraph P3 Regular</ParagraphP3>
          <ParagraphP3 weight="semibold">Paragraph P3 SemiBold</ParagraphP3>
          <ParagraphP3 weight="bold">Paragraph P3 Bold</ParagraphP3>
          <ParagraphP3 weight="extrabold">Paragraph P3 ExtraBold</ParagraphP3>
        </div>

        <div className="flex gap-4">
          <ButtonText weight="regular">Button Text Regular</ButtonText>
          <ButtonText weight="semibold">Button Text SemiBold</ButtonText>
          <ButtonText weight="bold">Button Text Bold</ButtonText>
          <ButtonText weight="extrabold">Button Text ExtraBold</ButtonText>
        </div>

        <div className="flex gap-4">
          <ButtonText2 weight="regular">Button Text 2 Regular</ButtonText2>
          <ButtonText2 weight="semibold">Button Text 2 SemiBold</ButtonText2>
          <ButtonText2 weight="bold">Button Text 2 Bold</ButtonText2>
          <ButtonText2 weight="extrabold">Button Text 2 ExtraBold</ButtonText2>
        </div>

        <div className="flex gap-4">
          <ParagraphP1 weight="regular" className="underline">Paragraph P1 Regular</ParagraphP1>
          <ParagraphP1 weight="semibold" className="underline">Paragraph P1 SemiBold</ParagraphP1>
          <ParagraphP1 weight="bold" className="underline">Paragraph P1 Bold</ParagraphP1>
          <ParagraphP1 weight="extrabold" className="underline">Paragraph P1 ExtraBold</ParagraphP1>
        </div>

        {children}

        <footer>

        </footer>
      </body>
    </html>
  );
}
