import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";

import { DisplayText, DisplayTextM, SubHeading, HeadingH1, HeadingH2, HeadingH3, HeadingH4, HeadingH5, HeadingH6, ParagraphP1, ParagraphP2, ParagraphP3, ButtonText, ButtonText2 } from "@/components/Typography"; 

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Sebastian Pytka | Web Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sora.variable} antialiased`}
      >
        <Header />

        {children}

        <Footer />
      </body>
    </html>
  );
}
